package com.eyelinecom.whoisd.sads2.plugins.bitrix.services.api.handlers

import com.eyelinecom.whoisd.sads2.plugins.bitrix.utils.TemplateUtils

/**
 * author: Artem Voronov
 */
class EventParametersExamples {

  static final Map<String, String[]> USER_START_MESSAGING = new HashMap<>()
  static {
    addParameter(USER_START_MESSAGING, "domain", "company.bitrix24.ru")
    addParameter(USER_START_MESSAGING, "lang", "ru")
    addParameter(USER_START_MESSAGING, "ref_sid", "265")
    addParameter(USER_START_MESSAGING, "back_page", "BACK_PAGE_URL")
    addParameter(USER_START_MESSAGING, "event.order", "EVENT_ORDER")
    addParameter(USER_START_MESSAGING, "subscriber", "USER_ID")
    addParameter(USER_START_MESSAGING, "abonent", "USER_ID")
    addParameter(USER_START_MESSAGING, "protocol", "telegram")
    addParameter(USER_START_MESSAGING, "user_id", "USER_ID")
    addParameter(USER_START_MESSAGING, "service", "SERVICE_ID")
    addParameter(USER_START_MESSAGING, "event.text", "go")
    addParameter(USER_START_MESSAGING, "event.referer", "http://hosting-api-test.eyeline.mobi/start?protocol=telegram&event.order=975952463&subscriber=USER_ID&user_id=USER_ID&service=SERVICE_ID&event.type=text&event.text=%2Fstart&event=message&lang=ru&abonent=USER_ID&serviceId=SERVICE_ID&sid=265")
    addParameter(USER_START_MESSAGING, "event", "link")
    addParameter(USER_START_MESSAGING, "serviceId", "SERVICE_ID")

  }

  static final Map<String, String[]> MESSAGE_FROM_USER = new HashMap<>()
  static {
    addParameter(MESSAGE_FROM_USER, "domain", "company.bitrix24.ru")
    addParameter(MESSAGE_FROM_USER, "lang", "ru")
    addParameter(MESSAGE_FROM_USER, "redirect_back_page", "http://plugins.miniapps.run/bitrix?domain=company.bitrix24.ru&amp;user_id=USER_ID&amp;service=SERVICE_ID&amp;protocol=telegramlang=ru&amp;back_page_original=http%3A%2F%2Fhosting-api-test.eyeline.mobi%2Findex%3Fsid%3D265%26amp%3Bsver%3D787%26amp%3Bpid%3D21%26amp%3Banswer%3Dback_page")
    addParameter(MESSAGE_FROM_USER, "event.text", "yrdy")
    addParameter(MESSAGE_FROM_USER, "event.order", "975952465")
    addParameter(MESSAGE_FROM_USER, "subscriber", "USER_ID")
    addParameter(MESSAGE_FROM_USER, "abonent", "USER_ID")
    addParameter(MESSAGE_FROM_USER, "protocol", "telegram")
    addParameter(MESSAGE_FROM_USER, "user_id", "USER_ID")
    addParameter(MESSAGE_FROM_USER, "service", "SERVICE_ID")
    addParameter(MESSAGE_FROM_USER, "event.type", "text")
    addParameter(MESSAGE_FROM_USER, "event", "message")
    addParameter(MESSAGE_FROM_USER, "serviceId", "SERVICE_ID")
  }

  static final Map<String, String[]> USER_STOP_MESSAGING = new HashMap<>()
  static {
    addParameter(USER_STOP_MESSAGING, "subscriber", "USER_ID")
    addParameter(USER_STOP_MESSAGING, "abonent", "USER_ID")
    addParameter(USER_STOP_MESSAGING, "protocol", "telegram")
    addParameter(USER_STOP_MESSAGING, "redirect_back_page", "http://plugins.miniapps.run/bitrix?domain=company.bitrix24.ru&amp;user_id=USER_ID&amp;service=SERVICE_ID&amp;protocol=telegramlang=ru&amp;back_page_original=http%3A%2F%2Fhosting-api-test.eyeline.mobi%2Findex%3Fsid%3D265%26amp%3Bsver%3D787%26amp%3Bpid%3D21%26amp%3Banswer%3Dback_page")
    addParameter(USER_STOP_MESSAGING, "user_id", "USER_ID")
    addParameter(USER_STOP_MESSAGING, "service", "SERVICE_ID")
    addParameter(USER_STOP_MESSAGING, "domain", "company.bitrix24.ru")
    addParameter(USER_STOP_MESSAGING, "lang", "ru")
    addParameter(USER_STOP_MESSAGING, "serviceId", "SERVICE_ID")
    addParameter(USER_STOP_MESSAGING, "bad_command", "⁣Назад")
    addParameter(USER_STOP_MESSAGING, "event.order", "975952466")
    addParameter(USER_STOP_MESSAGING, "event.type", "text")
    addParameter(USER_STOP_MESSAGING, "event.text", TemplateUtils.BACK_BUTTON_RU)
    addParameter(USER_STOP_MESSAGING, "event", "message")
  }

  static final Map<String, String[]> APP_INSTALL = new HashMap<>()
  static {
    addParameter(APP_INSTALL, "event", "ONAPPINSTALL")
    addParameter(APP_INSTALL, "data[VERSION]", "1")
    addParameter(APP_INSTALL, "data[LANGUAGE_ID]", "ru")
    addParameter(APP_INSTALL, "ts", "1492162568")
    addParameter(APP_INSTALL, "auth[access_token]", "TOKEN")
    addParameter(APP_INSTALL, "auth[expires_in]", "3600")
    addParameter(APP_INSTALL, "auth[scope]", "imbot")
    addParameter(APP_INSTALL, "auth[domain]", "company.bitrix24.ru")
    addParameter(APP_INSTALL, "auth[server_endpoint]", "https://oauth.bitrix.info/rest/")
    addParameter(APP_INSTALL, "auth[status]", "L")
    addParameter(APP_INSTALL, "auth[client_endpoint]", "https://company.bitrix24.ru/rest/")
    addParameter(APP_INSTALL, "auth[member_id]", "USER_ID")
    addParameter(APP_INSTALL, "auth[user_id]", "50")
    addParameter(APP_INSTALL, "auth[refresh_token]", "TOKEN")
    addParameter(APP_INSTALL, "auth[application_token]", "TOKEN")
  }

  static final Map<String, String[]> BOT_JOIN_GROUP_CHAT = new HashMap<>()
  static {
    addParameter(BOT_JOIN_GROUP_CHAT, "event", "ONIMBOTJOINCHAT")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[BOT][72][domain]", "company.bitrix24.ru")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[BOT][72][member_id]", "USER_ID")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[BOT][72][application_token]", "TOKEN")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[BOT][72][AUTH][domain]", "company.bitrix24.ru")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[BOT][72][AUTH][member_id]", "USER_ID")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[BOT][72][AUTH][application_token]", "TOKEN")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[BOT][72][BOT_ID]", "72")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[BOT][72][BOT_CODE]", "company.chatbot")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[PARAMS][CHAT_TYPE]", "C")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[PARAMS][MESSAGE_TYPE]", "C")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[PARAMS][BOT_ID]", "72")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[PARAMS][USER_ID]", "50")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[PARAMS][CHAT_ID]", "160")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[PARAMS][CHAT_AUTHOR_ID]", "50")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[PARAMS][CHAT_ENTITY_TYPE]", "")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[PARAMS][DIALOG_ID]", "chat160")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[PARAMS][LANGUAGE]", "ru")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[USER][ID]", "50")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[USER][NAME]", "Artem Voronov")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[USER][FIRST_NAME]", "Artem")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[USER][LAST_NAME]", "Voronov")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[USER][WORK_POSITION]", "")
    addParameter(BOT_JOIN_GROUP_CHAT, "data[USER][GENDER]", "M")
    addParameter(BOT_JOIN_GROUP_CHAT, "ts", "1492162606")
    addParameter(BOT_JOIN_GROUP_CHAT, "auth[access_token]", "TOKEN")
    addParameter(BOT_JOIN_GROUP_CHAT, "auth[expires_in]", "3600")
    addParameter(BOT_JOIN_GROUP_CHAT, "auth[scope]", "imbot")
    addParameter(BOT_JOIN_GROUP_CHAT, "auth[domain]", "company.bitrix24.ru")
    addParameter(BOT_JOIN_GROUP_CHAT, "auth[server_endpoint]", "https://oauth.bitrix.info/rest/")
    addParameter(BOT_JOIN_GROUP_CHAT, "auth[status]", "L")
    addParameter(BOT_JOIN_GROUP_CHAT, "auth[client_endpoint]", "https://company.bitrix24.ru/rest/")
    addParameter(BOT_JOIN_GROUP_CHAT, "auth[member_id]", "USER_ID")
    addParameter(BOT_JOIN_GROUP_CHAT, "auth[user_id]", "50")
    addParameter(BOT_JOIN_GROUP_CHAT, "auth[application_token]", "TOKEN")
  }

  static final Map<String, String[]> BOT_JOIN_PRIVATE_CHAT = new HashMap<>()
  static {
    addParameter(BOT_JOIN_PRIVATE_CHAT, "event", "ONIMBOTJOINCHAT")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[BOT][176][domain]", "company.bitrix24.ru")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[BOT][176][member_id]", "USER_ID")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[BOT][176][application_token]", "TOKEN")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[BOT][176][AUTH][domain]", "company.bitrix24.ru")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[BOT][176][AUTH][member_id]", "USER_ID")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[BOT][176][AUTH][application_token]", "TOKEN")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[BOT][176][BOT_ID]", "176")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[BOT][176][BOT_CODE]", "company.chatbot")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[PARAMS][CHAT_TYPE]", "P")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[PARAMS][MESSAGE_TYPE]", "P")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[PARAMS][BOT_ID]", "176")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[PARAMS][USER_ID]", "50")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[PARAMS][TO_USER_ID]", "176")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[PARAMS][FROM_USER_ID]", "50")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[PARAMS][DIALOG_ID]", "50")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[PARAMS][LANGUAGE]", "ru")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[USER][ID]", "50")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[USER][NAME]", "Артем Воронов")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[USER][FIRST_NAME]", "Артем")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[USER][LAST_NAME]", "Воронов")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[USER][WORK_POSITION]", "")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "data[USER][GENDER]", "M")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "ts", "1493807443")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "auth[access_token]", "TOKEN")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "auth[expires_in]", "3600")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "auth[scope]", "imbot")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "auth[domain]", "company.bitrix24.ru")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "auth[server_endpoint]", "https://oauth.bitrix.info/rest/")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "auth[status]", "L")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "auth[client_endpoint]", "https://company.bitrix24.ru/rest/")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "auth[member_id]", "USER_ID")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "auth[user_id]", "50")
    addParameter(BOT_JOIN_PRIVATE_CHAT, "auth[application_token]", "TOKEN")
  }

  static final Map<String, String[]> MESSAGE_FROM_OPERATOR_GROUP_CHAT = new HashMap<>()
  static {
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "event", "ONIMBOTMESSAGEADD")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[BOT][108][domain]", "company.bitrix24.ru")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[BOT][108][member_id]", "USER_ID")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[BOT][108][application_token]", "TOKEN")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[BOT][108][AUTH][domain]", "company.bitrix24.ru")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[BOT][108][AUTH][member_id]", "USER_ID")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[BOT][108][AUTH][application_token]", "TOKEN")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[BOT][108][BOT_ID]", "108")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[BOT][108][BOT_CODE]", "company.chatbot")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][FROM_USER_ID]", "50")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][TO_CHAT_ID]", "160")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][MESSAGE]", "test")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][SILENT_CONNECTOR]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][MESSAGE_TYPE]", "O")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][SKIP_COMMAND]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][SKIP_CONNECTOR]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][IMPORTANT_CONNECTOR]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][AUTHOR_ID]", "50")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][SKIP_USER_CHECK]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][CHAT_ID]", "160")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][CHAT_AUTHOR_ID]", "50")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][CHAT_ENTITY_TYPE]", "")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][CHAT_ENTITY_ID]", "")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][BOT_IN_CHAT][108]", "108")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][COMMAND_CONTEXT]", "TEXTAREA")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][MESSAGE_ORIGINAL]", "[USER=108]BotoBot2000[/USER] test")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][DIALOG_ID]", "chat160")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][MESSAGE_ID]", "5086")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][CHAT_TYPE]", "O")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[PARAMS][LANGUAGE]", "ru")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[USER][ID]", "50")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[USER][NAME]", "Артем Воронов")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[USER][FIRST_NAME]", "Артем")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[USER][LAST_NAME]", "Воронов")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[USER][WORK_POSITION]", "")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[USER][GENDER]", "M")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[USER][IS_BOT]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[USER][IS_CONNECTOR]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[USER][IS_NETWORK]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "data[USER][IS_EXTRANET]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "ts", "1493100066")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "auth[access_token]", "TOKEN")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "auth[expires_in]", "3600")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "auth[scope]", "imbot")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "auth[domain]", "company.bitrix24.ru")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "auth[server_endpoint]", "https://oauth.bitrix.info/rest/")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "auth[status]", "L")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "auth[client_endpoint]", "https://company.bitrix24.ru/rest/")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "auth[member_id]", "USER_ID")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "auth[user_id]", "50")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "auth[refresh_token]", "TOKEN")
    addParameter(MESSAGE_FROM_OPERATOR_GROUP_CHAT, "auth[application_token]", "TOKEN")
  }

  static final Map<String, String[]> MESSAGE_FROM_OPERATOR_PRIVATE_CHAT = new HashMap<>()
  static {
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "event", "ONIMBOTMESSAGEADD")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[BOT][72][domain]", "company.bitrix24.ru")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[BOT][72][member_id]", "USER_ID")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[BOT][72][application_token]", "TOKEN")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[BOT][72][AUTH][domain]", "company.bitrix24.ru")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[BOT][72][AUTH][member_id]", "USER_ID")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[BOT][72][AUTH][application_token]", "TOKEN")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[BOT][72][BOT_ID]", "72")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[BOT][72][BOT_CODE]", "company.chatbot")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[PARAMS][FROM_USER_ID]", "50")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[PARAMS][TO_USER_ID]", "72")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[PARAMS][MESSAGE]", "test")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[PARAMS][MESSAGE_TYPE]", "P")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[PARAMS][SKIP_COMMAND]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[PARAMS][SKIP_CONNECTOR]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[PARAMS][IMPORTANT_CONNECTOR]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[PARAMS][SILENT_CONNECTOR]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[PARAMS][AUTHOR_ID]", "50")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[PARAMS][CHAT_ID]", "172")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[PARAMS][COMMAND_CONTEXT]", "TEXTAREA")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[PARAMS][DIALOG_ID]", "50")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[PARAMS][MESSAGE_ID]", "2690")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[PARAMS][CHAT_TYPE]", "P")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[PARAMS][LANGUAGE]", "ru")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[USER][ID]", "50")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[USER][NAME]", "Artem Voronov")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[USER][FIRST_NAME]", "Artem")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[USER][LAST_NAME]", "Voronov")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[USER][WORK_POSITION]", "")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[USER][GENDER]", "M")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[USER][IS_BOT]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[USER][IS_CONNECTOR]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[USER][IS_NETWORK]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "data[USER][IS_EXTRANET]", "N")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "ts", "1492163323")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "auth[access_token]", "TOKEN")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "auth[expires_in]", "3600")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "auth[scope]", "imbot")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "auth[domain]", "company.bitrix24.ru")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "auth[server_endpoint]", "https://oauth.bitrix.info/rest/")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "auth[status]", "L")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "auth[client_endpoint]", "https://company.bitrix24.ru/rest/")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "auth[member_id]", "USER_ID")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "auth[user_id]", "50")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "auth[refresh_token]", "TOKEN")
    addParameter(MESSAGE_FROM_OPERATOR_PRIVATE_CHAT, "auth[application_token]", "TOKEN")
  }

  private static final Map<String, String[]> COMMAND_GROUP_CHAT = new HashMap<>()
  static {
    addParameter(COMMAND_GROUP_CHAT, "event", "ONIMCOMMANDADD")
    addParameter(COMMAND_GROUP_CHAT, "data[COMMAND][34][domain]", "company.bitrix24.ru")
    addParameter(COMMAND_GROUP_CHAT, "data[COMMAND][34][member_id]", "USER_ID")
    addParameter(COMMAND_GROUP_CHAT, "data[COMMAND][34][application_token]", "TOKEN")
    addParameter(COMMAND_GROUP_CHAT, "data[COMMAND][34][AUTH][domain]", "company.bitrix24.ru")
    addParameter(COMMAND_GROUP_CHAT, "data[COMMAND][34][AUTH][member_id]", "USER_ID")
    addParameter(COMMAND_GROUP_CHAT, "data[COMMAND][34][AUTH][application_token]", "TOKEN")
    addParameter(COMMAND_GROUP_CHAT, "data[COMMAND][34][BOT_ID]", "72")
    addParameter(COMMAND_GROUP_CHAT, "data[COMMAND][34][BOT_CODE]", "company.chatbot")
    addParameter(COMMAND_GROUP_CHAT, "data[COMMAND][34][COMMAND_ID]", "34")
    addParameter(COMMAND_GROUP_CHAT, "data[COMMAND][34][COMMAND_PARAMS]", "")
    addParameter(COMMAND_GROUP_CHAT, "data[COMMAND][34][COMMAND_CONTEXT]", "TEXTAREA")
    addParameter(COMMAND_GROUP_CHAT, "data[COMMAND][34][MESSAGE_ID]", "2682")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][FROM_USER_ID]", "50")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][TO_CHAT_ID]", "160")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][SILENT_CONNECTOR]", "N")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][MESSAGE_TYPE]", "O")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][SKIP_COMMAND]", "N")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][SKIP_CONNECTOR]", "N")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][IMPORTANT_CONNECTOR]", "N")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][AUTHOR_ID]", "50")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][SKIP_USER_CHECK]", "N")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][CHAT_ID]", "160")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][CHAT_AUTHOR_ID]", "50")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][CHAT_ENTITY_TYPE]", "")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][CHAT_ENTITY_ID]", "")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][BOT_IN_CHAT][72]", "72")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][DIALOG_ID]", "chat160")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][MESSAGE_ID]", "2682")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][CHAT_TYPE]", "O")
    addParameter(COMMAND_GROUP_CHAT, "data[PARAMS][LANGUAGE]", "ru")
    addParameter(COMMAND_GROUP_CHAT, "data[USER][ID]", "50")
    addParameter(COMMAND_GROUP_CHAT, "data[USER][NAME]", "Artem Voronov")
    addParameter(COMMAND_GROUP_CHAT, "data[USER][FIRST_NAME]", "Artem")
    addParameter(COMMAND_GROUP_CHAT, "data[USER][LAST_NAME]", "Voronov")
    addParameter(COMMAND_GROUP_CHAT, "data[USER][WORK_POSITION]", "")
    addParameter(COMMAND_GROUP_CHAT, "data[USER][GENDER]", "M")
    addParameter(COMMAND_GROUP_CHAT, "ts", "1492163043")
    addParameter(COMMAND_GROUP_CHAT, "auth[access_token]", "TOKEN")
    addParameter(COMMAND_GROUP_CHAT, "auth[expires_in]", "3600")
    addParameter(COMMAND_GROUP_CHAT, "auth[scope]", "imbot")
    addParameter(COMMAND_GROUP_CHAT, "auth[domain]", "company.bitrix24.ru")
    addParameter(COMMAND_GROUP_CHAT, "auth[server_endpoint]", "https://oauth.bitrix.info/rest/")
    addParameter(COMMAND_GROUP_CHAT, "auth[status]", "L")
    addParameter(COMMAND_GROUP_CHAT, "auth[client_endpoint]", "https://company.bitrix24.ru/rest/")
    addParameter(COMMAND_GROUP_CHAT, "auth[member_id]", "USER_ID")
    addParameter(COMMAND_GROUP_CHAT, "auth[user_id]", "50")
    addParameter(COMMAND_GROUP_CHAT, "auth[refresh_token]", "TOKEN")
    addParameter(COMMAND_GROUP_CHAT, "auth[application_token]", "TOKEN")
  }

  static final Map<String, String[]> HELP_COMMAND_GROUP_CHAT = new HashMap<>()
  static final Map<String, String[]> INFO_COMMAND_GROUP_CHAT = new HashMap<>()
  static final Map<String, String[]> START_COMMAND_GROUP_CHAT = new HashMap<>()
  static final Map<String, String[]> STOP_COMMAND_GROUP_CHAT = new HashMap<>()
  static {
    HELP_COMMAND_GROUP_CHAT.putAll(COMMAND_GROUP_CHAT)
    INFO_COMMAND_GROUP_CHAT.putAll(COMMAND_GROUP_CHAT)
    START_COMMAND_GROUP_CHAT.putAll(COMMAND_GROUP_CHAT)
    STOP_COMMAND_GROUP_CHAT.putAll(COMMAND_GROUP_CHAT)

    addParameter(HELP_COMMAND_GROUP_CHAT, "data[PARAMS][MESSAGE]", "/info")
    addParameter(HELP_COMMAND_GROUP_CHAT, "data[COMMAND][34][COMMAND]", "info")

    addParameter(INFO_COMMAND_GROUP_CHAT, "data[PARAMS][MESSAGE]", "/info")
    addParameter(INFO_COMMAND_GROUP_CHAT, "data[COMMAND][34][COMMAND]", "info")

    addParameter(START_COMMAND_GROUP_CHAT, "data[PARAMS][MESSAGE]", "/info")
    addParameter(START_COMMAND_GROUP_CHAT, "data[COMMAND][34][COMMAND]", "info")

    addParameter(STOP_COMMAND_GROUP_CHAT, "data[PARAMS][MESSAGE]", "/info")
    addParameter(STOP_COMMAND_GROUP_CHAT, "data[COMMAND][34][COMMAND]", "info")
  }

  private static final Map<String, String[]> COMMAND_PRIVATE_CHAT = new HashMap<>()
  static {
    addParameter(COMMAND_PRIVATE_CHAT, "event", "ONIMCOMMANDADD")
    addParameter(COMMAND_PRIVATE_CHAT, "data[COMMAND][34][domain]", "company.bitrix24.ru")
    addParameter(COMMAND_PRIVATE_CHAT, "data[COMMAND][34][member_id]", "USER_ID")
    addParameter(COMMAND_PRIVATE_CHAT, "data[COMMAND][34][application_token]", "TOKEN")
    addParameter(COMMAND_PRIVATE_CHAT, "data[COMMAND][34][AUTH][domain]", "company.bitrix24.ru")
    addParameter(COMMAND_PRIVATE_CHAT, "data[COMMAND][34][AUTH][member_id]", "USER_ID")
    addParameter(COMMAND_PRIVATE_CHAT, "data[COMMAND][34][AUTH][application_token]", "TOKEN")
    addParameter(COMMAND_PRIVATE_CHAT, "data[COMMAND][34][BOT_ID]", "72")
    addParameter(COMMAND_PRIVATE_CHAT, "data[COMMAND][34][BOT_CODE]", "company.chatbot")
    addParameter(COMMAND_PRIVATE_CHAT, "data[COMMAND][34][COMMAND_ID]", "34")
    addParameter(COMMAND_PRIVATE_CHAT, "data[COMMAND][34][COMMAND_PARAMS]", "")
    addParameter(COMMAND_PRIVATE_CHAT, "data[COMMAND][34][COMMAND_CONTEXT]", "TEXTAREA")
    addParameter(COMMAND_PRIVATE_CHAT, "data[COMMAND][34][MESSAGE_ID]", "2684")
    addParameter(COMMAND_PRIVATE_CHAT, "data[PARAMS][FROM_USER_ID]", "50")
    addParameter(COMMAND_PRIVATE_CHAT, "data[PARAMS][TO_USER_ID]", "72")
    addParameter(COMMAND_PRIVATE_CHAT, "data[PARAMS][MESSAGE_TYPE]", "P")
    addParameter(COMMAND_PRIVATE_CHAT, "data[PARAMS][SKIP_COMMAND]", "N")
    addParameter(COMMAND_PRIVATE_CHAT, "data[PARAMS][SKIP_CONNECTOR]", "N")
    addParameter(COMMAND_PRIVATE_CHAT, "data[PARAMS][IMPORTANT_CONNECTOR]", "N")
    addParameter(COMMAND_PRIVATE_CHAT, "data[PARAMS][SILENT_CONNECTOR]", "N")
    addParameter(COMMAND_PRIVATE_CHAT, "data[PARAMS][AUTHOR_ID]", "50")
    addParameter(COMMAND_PRIVATE_CHAT, "data[PARAMS][CHAT_ID]", "172")
    addParameter(COMMAND_PRIVATE_CHAT, "data[PARAMS][DIALOG_ID]", "50")
    addParameter(COMMAND_PRIVATE_CHAT, "data[PARAMS][MESSAGE_ID]", "2684")
    addParameter(COMMAND_PRIVATE_CHAT, "data[PARAMS][CHAT_TYPE]", "P")
    addParameter(COMMAND_PRIVATE_CHAT, "data[PARAMS][LANGUAGE]", "ru")
    addParameter(COMMAND_PRIVATE_CHAT, "data[USER][ID]", "50")
    addParameter(COMMAND_PRIVATE_CHAT, "data[USER][NAME]", "Artem Voronov")
    addParameter(COMMAND_PRIVATE_CHAT, "data[USER][FIRST_NAME]", "Artem")
    addParameter(COMMAND_PRIVATE_CHAT, "data[USER][LAST_NAME]", "Voronov")
    addParameter(COMMAND_PRIVATE_CHAT, "data[USER][WORK_POSITION]", "")
    addParameter(COMMAND_PRIVATE_CHAT, "data[USER][GENDER]", "M")
    addParameter(COMMAND_PRIVATE_CHAT, "ts", "1492163064")
    addParameter(COMMAND_PRIVATE_CHAT, "auth[access_token]", "TOKEN")
    addParameter(COMMAND_PRIVATE_CHAT, "auth[expires_in]", "3600")
    addParameter(COMMAND_PRIVATE_CHAT, "auth[scope]", "imbot")
    addParameter(COMMAND_PRIVATE_CHAT, "auth[domain]", "company.bitrix24.ru")
    addParameter(COMMAND_PRIVATE_CHAT, "auth[server_endpoint]", "https://oauth.bitrix.info/rest/")
    addParameter(COMMAND_PRIVATE_CHAT, "auth[status]", "L")
    addParameter(COMMAND_PRIVATE_CHAT, "auth[client_endpoint]", "https://company.bitrix24.ru/rest/")
    addParameter(COMMAND_PRIVATE_CHAT, "auth[member_id]", "USER_ID")
    addParameter(COMMAND_PRIVATE_CHAT, "auth[user_id]", "50")
    addParameter(COMMAND_PRIVATE_CHAT, "auth[refresh_token]", "TOKEN")
    addParameter(COMMAND_PRIVATE_CHAT, "auth[application_token]", "TOKEN")
  }

  static final Map<String, String[]> HELP_COMMAND_PRIVATE_CHAT = new HashMap<>()
  static final Map<String, String[]> INFO_COMMAND_PRIVATE_CHAT = new HashMap<>()
  static final Map<String, String[]> START_COMMAND_PRIVATE_CHAT = new HashMap<>()
  static final Map<String, String[]> STOP_COMMAND_PRIVATE_CHAT = new HashMap<>()
  static {
    HELP_COMMAND_PRIVATE_CHAT.putAll(COMMAND_PRIVATE_CHAT)
    INFO_COMMAND_PRIVATE_CHAT.putAll(COMMAND_PRIVATE_CHAT)
    START_COMMAND_PRIVATE_CHAT.putAll(COMMAND_PRIVATE_CHAT)
    STOP_COMMAND_PRIVATE_CHAT.putAll(COMMAND_PRIVATE_CHAT)

    addParameter(HELP_COMMAND_PRIVATE_CHAT, "data[PARAMS][MESSAGE]", "/info")
    addParameter(HELP_COMMAND_PRIVATE_CHAT, "data[COMMAND][34][COMMAND]", "info")

    addParameter(INFO_COMMAND_PRIVATE_CHAT, "data[PARAMS][MESSAGE]", "/info")
    addParameter(INFO_COMMAND_PRIVATE_CHAT, "data[COMMAND][34][COMMAND]", "info")

    addParameter(START_COMMAND_PRIVATE_CHAT, "data[PARAMS][MESSAGE]", "/info")
    addParameter(START_COMMAND_PRIVATE_CHAT, "data[COMMAND][34][COMMAND]", "info")

    addParameter(STOP_COMMAND_PRIVATE_CHAT, "data[PARAMS][MESSAGE]", "/info")
    addParameter(STOP_COMMAND_PRIVATE_CHAT, "data[COMMAND][34][COMMAND]", "info")
  }

  private static addParameter(Map<String, String[]> parameters, String key, String value) {
    parameters.put(key, [value] as String[])
  }

}
