package com.eyelinecom.whoisd.sads2.plugins.bitrix.services.api.handlers

/**
 * author: Artem Voronov
 */
class Examples {

  static final Map<String, String[]> EVENT_LINK_PARAMETERS = new HashMap<>()
  static {
    addParameter(EVENT_LINK_PARAMETERS, "event", "link")
    addParameter(EVENT_LINK_PARAMETERS, "domain", "company.bitrix24.ru")
    addParameter(EVENT_LINK_PARAMETERS, "ref_sid", "660")
    addParameter(EVENT_LINK_PARAMETERS, "back_page", "http://hosting-api-test.eyeline.mobi/index?sid=660&sver=5&pid=2&answer=back_page")
    addParameter(EVENT_LINK_PARAMETERS, "event.order", "1492417681793")
    addParameter(EVENT_LINK_PARAMETERS, "subscriber", "9594d3a1-a080-4f18-bdc6-3d4ec6dd4a33")
    addParameter(EVENT_LINK_PARAMETERS, "abonent", "9594d3a1-a080-4f18-bdc6-3d4ec6dd4a33")
    addParameter(EVENT_LINK_PARAMETERS, "protocol", "viber")
    addParameter(EVENT_LINK_PARAMETERS, "user_id", "9594d3a1-a080-4f18-bdc6-3d4ec6dd4a33")
    addParameter(EVENT_LINK_PARAMETERS, "service", "lk.64.1492410911647")
    addParameter(EVENT_LINK_PARAMETERS, "event.text", "Задать вопрос оператору")
    addParameter(EVENT_LINK_PARAMETERS, "event.referer", "http://hosting-api-test.eyeline.mobi/start?protocol=viber&event.order=1492417678059&subscriber=9594d3a1-a080-4f18-bdc6-3d4ec6dd4a33&user_id=9594d3a1-a080-4f18-bdc6-3d4ec6dd4a33&service=lk.64.1492410911647&event.type=text&event.text=Start&event=message&lang=en&abonent=9594d3a1-a080-4f18-bdc6-3d4ec6dd4a33&serviceId=lk.64.1492410911647&sid=660")
    addParameter(EVENT_LINK_PARAMETERS, "lang", "en")
    addParameter(EVENT_LINK_PARAMETERS, "serviceId", "lk.64.1492410911647")
  }

  static final Map<String, String[]> EVENT_MESSAGE_PARAMETERS = new HashMap<>()
  static {
    addParameter(EVENT_MESSAGE_PARAMETERS, "domain", "company.bitrix24.ru")
    addParameter(EVENT_MESSAGE_PARAMETERS, "event.text", "привет")
    addParameter(EVENT_MESSAGE_PARAMETERS, "protocol", "telegram")
    addParameter(EVENT_MESSAGE_PARAMETERS, "event.order", "49713106")
    addParameter(EVENT_MESSAGE_PARAMETERS, "subscriber", "5a865fae-f6bf-415e-8657-7a7235105c9e")
    addParameter(EVENT_MESSAGE_PARAMETERS, "user_id", "5a865fae-f6bf-415e-8657-7a7235105c9e")
    addParameter(EVENT_MESSAGE_PARAMETERS, "service", "lk.64.1492410911647")
    addParameter(EVENT_MESSAGE_PARAMETERS, "event.type", "text")
    addParameter(EVENT_MESSAGE_PARAMETERS, "event", "message")
    addParameter(EVENT_MESSAGE_PARAMETERS, "lang", "en")
    addParameter(EVENT_MESSAGE_PARAMETERS, "abonent", "5a865fae-f6bf-415e-8657-7a7235105c9e")
    addParameter(EVENT_MESSAGE_PARAMETERS, "serviceId", "lk.64.1492410911647")
  }

  static final Map<String, String[]> EVENT_APP_INSTALL_PARAMETERS = new HashMap<>()
  static {
    addParameter(EVENT_APP_INSTALL_PARAMETERS, "event", "ONAPPINSTALL")
    addParameter(EVENT_APP_INSTALL_PARAMETERS, "data[VERSION]", "1")
    addParameter(EVENT_APP_INSTALL_PARAMETERS, "data[LANGUAGE_ID]", "ru")
    addParameter(EVENT_APP_INSTALL_PARAMETERS, "ts", "1492162568")
    addParameter(EVENT_APP_INSTALL_PARAMETERS, "auth[access_token]", "TOKEN")
    addParameter(EVENT_APP_INSTALL_PARAMETERS, "auth[expires_in]", "3600")
    addParameter(EVENT_APP_INSTALL_PARAMETERS, "auth[scope]", "imbot")
    addParameter(EVENT_APP_INSTALL_PARAMETERS, "auth[domain]", "company.bitrix24.ru")
    addParameter(EVENT_APP_INSTALL_PARAMETERS, "auth[server_endpoint]", "https://oauth.bitrix.info/rest/")
    addParameter(EVENT_APP_INSTALL_PARAMETERS, "auth[status]", "L")
    addParameter(EVENT_APP_INSTALL_PARAMETERS, "auth[client_endpoint]", "https://company.bitrix24.ru/rest/")
    addParameter(EVENT_APP_INSTALL_PARAMETERS, "auth[member_id]", "USER_ID")
    addParameter(EVENT_APP_INSTALL_PARAMETERS, "auth[user_id]", "50")
    addParameter(EVENT_APP_INSTALL_PARAMETERS, "auth[refresh_token]", "TOKEN")
    addParameter(EVENT_APP_INSTALL_PARAMETERS, "auth[application_token]", "TOKEN")
  }

  static final Map<String, String[]> EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS = new HashMap<>()
  static {
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "event", "ONIMBOTJOINCHAT")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[BOT][72][domain]", "company.bitrix24.ru")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[BOT][72][member_id]", "USER_ID")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[BOT][72][application_token]", "TOKEN")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[BOT][72][AUTH][domain]", "company.bitrix24.ru")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[BOT][72][AUTH][member_id]", "USER_ID")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[BOT][72][AUTH][application_token]", "TOKEN")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[BOT][72][BOT_ID]", "72")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[BOT][72][BOT_CODE]", "company.chatbot")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[PARAMS][CHAT_TYPE]", "C")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[PARAMS][MESSAGE_TYPE]", "C")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[PARAMS][BOT_ID]", "72")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[PARAMS][USER_ID]", "50")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[PARAMS][CHAT_ID]", "160")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[PARAMS][CHAT_AUTHOR_ID]", "50")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[PARAMS][CHAT_ENTITY_TYPE]", "")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[PARAMS][DIALOG_ID]", "chat160")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[PARAMS][LANGUAGE]", "ru")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[USER][ID]", "50")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[USER][NAME]", "Artem Voronov")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[USER][FIRST_NAME]", "Artem")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[USER][LAST_NAME]", "Voronov")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[USER][WORK_POSITION]", "")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "data[USER][GENDER]", "M")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "ts", "1492162606")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "auth[access_token]", "TOKEN")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "auth[expires_in]", "3600")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "auth[scope]", "imbot")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "auth[domain]", "company.bitrix24.ru")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "auth[server_endpoint]", "https://oauth.bitrix.info/rest/")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "auth[status]", "L")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "auth[client_endpoint]", "https://company.bitrix24.ru/rest/")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "auth[member_id]", "USER_ID")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "auth[user_id]", "50")
    addParameter(EVENT_BOT_JOIN_GROUP_CHAT_PARAMETERS, "auth[application_token]", "TOKEN")
  }

  static final Map<String, String[]> EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS = new HashMap<>()
  static {
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "event", "ONIMBOTJOINCHAT")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[BOT][176][domain]", "company.bitrix24.ru")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[BOT][176][member_id]", "USER_ID")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[BOT][176][application_token]", "TOKEN")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[BOT][176][AUTH][domain]", "company.bitrix24.ru")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[BOT][176][AUTH][member_id]", "USER_ID")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[BOT][176][AUTH][application_token]", "TOKEN")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[BOT][176][BOT_ID]", "176")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[BOT][176][BOT_CODE]", "company.chatbot")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][CHAT_TYPE]", "P")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][MESSAGE_TYPE]", "P")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][BOT_ID]", "176")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][USER_ID]", "50")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][TO_USER_ID]", "176")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][FROM_USER_ID]", "50")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][DIALOG_ID]", "50")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][LANGUAGE]", "ru")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[USER][ID]", "50")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[USER][NAME]", "Артем Воронов")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[USER][FIRST_NAME]", "Артем")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[USER][LAST_NAME]", "Воронов")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[USER][WORK_POSITION]", "")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "data[USER][GENDER]", "M")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "ts", "1493807443")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "auth[access_token]", "TOKEN")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "auth[expires_in]", "3600")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "auth[scope]", "imbot")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "auth[domain]", "company.bitrix24.ru")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "auth[server_endpoint]", "https://oauth.bitrix.info/rest/")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "auth[status]", "L")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "auth[client_endpoint]", "https://company.bitrix24.ru/rest/")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "auth[member_id]", "USER_ID")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "auth[user_id]", "50")
    addParameter(EVENT_BOT_JOIN_PRIVATE_CHAT_PARAMETERS, "auth[application_token]", "TOKEN")
  }

  static final Map<String, String[]> EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS = new HashMap<>()
  static {
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "event", "ONIMBOTMESSAGEADD")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[BOT][108][domain]", "company.bitrix24.ru")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[BOT][108][member_id]", "USER_ID")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[BOT][108][application_token]", "TOKEN")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[BOT][108][AUTH][domain]", "company.bitrix24.ru")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[BOT][108][AUTH][member_id]", "USER_ID")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[BOT][108][AUTH][application_token]", "TOKEN")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[BOT][108][BOT_ID]", "108")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[BOT][108][BOT_CODE]", "company.chatbot")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][FROM_USER_ID]", "50")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][TO_CHAT_ID]", "160")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][MESSAGE]", "test")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][SILENT_CONNECTOR]", "N")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][MESSAGE_TYPE]", "O")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][SKIP_COMMAND]", "N")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][SKIP_CONNECTOR]", "N")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][IMPORTANT_CONNECTOR]", "N")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][AUTHOR_ID]", "50")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][SKIP_USER_CHECK]", "N")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][CHAT_ID]", "160")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][CHAT_AUTHOR_ID]", "50")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][CHAT_ENTITY_TYPE]", "")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][CHAT_ENTITY_ID]", "")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][BOT_IN_CHAT][108]", "108")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][COMMAND_CONTEXT]", "TEXTAREA")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][MESSAGE_ORIGINAL]", "[USER=108]BotoBot2000[/USER] test")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][DIALOG_ID]", "chat160")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][MESSAGE_ID]", "5086")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][CHAT_TYPE]", "O")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][LANGUAGE]", "ru")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[USER][ID]", "50")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[USER][NAME]", "Артем Воронов")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[USER][FIRST_NAME]", "Артем")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[USER][LAST_NAME]", "Воронов")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[USER][WORK_POSITION]", "")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[USER][GENDER]", "M")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[USER][IS_BOT]", "N")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[USER][IS_CONNECTOR]", "N")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[USER][IS_NETWORK]", "N")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "data[USER][IS_EXTRANET]", "N")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "ts", "1493100066")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "auth[access_token]", "TOKEN")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "auth[expires_in]", "3600")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "auth[scope]", "imbot")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "auth[domain]", "company.bitrix24.ru")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "auth[server_endpoint]", "https://oauth.bitrix.info/rest/")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "auth[status]", "L")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "auth[client_endpoint]", "https://company.bitrix24.ru/rest/")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "auth[member_id]", "USER_ID")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "auth[user_id]", "50")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "auth[refresh_token]", "TOKEN")
    addParameter(EVENT_MESSAGE_FROM_GROUP_CHAT_PARAMETERS, "auth[application_token]", "TOKEN")
  }

  static final Map<String, String[]> EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS = new HashMap<>()
  static {
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "event", "ONIMBOTMESSAGEADD")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[BOT][72][domain]", "company.bitrix24.ru")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[BOT][72][member_id]", "USER_ID")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[BOT][72][application_token]", "TOKEN")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[BOT][72][AUTH][domain]", "company.bitrix24.ru")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[BOT][72][AUTH][member_id]", "USER_ID")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[BOT][72][AUTH][application_token]", "TOKEN")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[BOT][72][BOT_ID]", "72")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[BOT][72][BOT_CODE]", "company.chatbot")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][FROM_USER_ID]", "50")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][TO_USER_ID]", "72")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][MESSAGE]", "test")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][MESSAGE_TYPE]", "P")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][SKIP_COMMAND]", "N")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][SKIP_CONNECTOR]", "N")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][IMPORTANT_CONNECTOR]", "N")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][SILENT_CONNECTOR]", "N")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][AUTHOR_ID]", "50")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][CHAT_ID]", "172")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][COMMAND_CONTEXT]", "TEXTAREA")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][DIALOG_ID]", "50")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][MESSAGE_ID]", "2690")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][CHAT_TYPE]", "P")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][LANGUAGE]", "ru")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[USER][ID]", "50")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[USER][NAME]", "Artem Voronov")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[USER][FIRST_NAME]", "Artem")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[USER][LAST_NAME]", "Voronov")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[USER][WORK_POSITION]", "")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[USER][GENDER]", "M")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[USER][IS_BOT]", "N")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[USER][IS_CONNECTOR]", "N")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[USER][IS_NETWORK]", "N")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "data[USER][IS_EXTRANET]", "N")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "ts", "1492163323")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "auth[access_token]", "TOKEN")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "auth[expires_in]", "3600")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "auth[scope]", "imbot")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "auth[domain]", "company.bitrix24.ru")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "auth[server_endpoint]", "https://oauth.bitrix.info/rest/")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "auth[status]", "L")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "auth[client_endpoint]", "https://company.bitrix24.ru/rest/")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "auth[member_id]", "USER_ID")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "auth[user_id]", "50")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "auth[refresh_token]", "TOKEN")
    addParameter(EVENT_MESSAGE_FROM_PRIVATE_CHAT_PARAMETERS, "auth[application_token]", "TOKEN")
  }

  static final Map<String, String[]> EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS = new HashMap<>()
  static {
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "event", "ONIMCOMMANDADD")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[COMMAND][34][domain]", "company.bitrix24.ru")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[COMMAND][34][member_id]", "USER_ID")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[COMMAND][34][application_token]", "TOKEN")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[COMMAND][34][AUTH][domain]", "company.bitrix24.ru")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[COMMAND][34][AUTH][member_id]", "USER_ID")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[COMMAND][34][AUTH][application_token]", "TOKEN")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[COMMAND][34][BOT_ID]", "72")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[COMMAND][34][BOT_CODE]", "company.chatbot")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[COMMAND][34][COMMAND]", "info")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[COMMAND][34][COMMAND_ID]", "34")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[COMMAND][34][COMMAND_PARAMS]", "")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[COMMAND][34][COMMAND_CONTEXT]", "TEXTAREA")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[COMMAND][34][MESSAGE_ID]", "2682")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][FROM_USER_ID]", "50")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][TO_CHAT_ID]", "160")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][MESSAGE]", "/info")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][SILENT_CONNECTOR]", "N")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][MESSAGE_TYPE]", "O")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][SKIP_COMMAND]", "N")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][SKIP_CONNECTOR]", "N")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][IMPORTANT_CONNECTOR]", "N")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][AUTHOR_ID]", "50")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][SKIP_USER_CHECK]", "N")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][CHAT_ID]", "160")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][CHAT_AUTHOR_ID]", "50")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][CHAT_ENTITY_TYPE]", "")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][CHAT_ENTITY_ID]", "")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][BOT_IN_CHAT][72]", "72")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][DIALOG_ID]", "chat160")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][MESSAGE_ID]", "2682")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][CHAT_TYPE]", "O")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[PARAMS][LANGUAGE]", "ru")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[USER][ID]", "50")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[USER][NAME]", "Artem Voronov")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[USER][FIRST_NAME]", "Artem")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[USER][LAST_NAME]", "Voronov")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[USER][WORK_POSITION]", "")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "data[USER][GENDER]", "M")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "ts", "1492163043")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "auth[access_token]", "TOKEN")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "auth[expires_in]", "3600")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "auth[scope]", "imbot")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "auth[domain]", "company.bitrix24.ru")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "auth[server_endpoint]", "https://oauth.bitrix.info/rest/")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "auth[status]", "L")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "auth[client_endpoint]", "https://company.bitrix24.ru/rest/")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "auth[member_id]", "USER_ID")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "auth[user_id]", "50")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "auth[refresh_token]", "TOKEN")
    addParameter(EVENT_COMMAND_FROM_GROUP_CHAT_PARAMETERS, "auth[application_token]", "TOKEN")
  }

  static final Map<String, String[]> EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS = new HashMap<>()
  static {
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "event", "ONIMCOMMANDADD")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[COMMAND][34][domain]", "company.bitrix24.ru")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[COMMAND][34][member_id]", "USER_ID")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[COMMAND][34][application_token]", "TOKEN")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[COMMAND][34][AUTH][domain]", "company.bitrix24.ru")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[COMMAND][34][AUTH][member_id]", "USER_ID")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[COMMAND][34][AUTH][application_token]", "TOKEN")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[COMMAND][34][BOT_ID]", "72")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[COMMAND][34][BOT_CODE]", "company.chatbot")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[COMMAND][34][COMMAND]", "info")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[COMMAND][34][COMMAND_ID]", "34")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[COMMAND][34][COMMAND_PARAMS]", "")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[COMMAND][34][COMMAND_CONTEXT]", "TEXTAREA")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[COMMAND][34][MESSAGE_ID]", "2684")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][FROM_USER_ID]", "50")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][TO_USER_ID]", "72")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][MESSAGE]", "/info")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][MESSAGE_TYPE]", "P")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][SKIP_COMMAND]", "N")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][SKIP_CONNECTOR]", "N")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][IMPORTANT_CONNECTOR]", "N")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][SILENT_CONNECTOR]", "N")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][AUTHOR_ID]", "50")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][CHAT_ID]", "172")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][DIALOG_ID]", "50")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][MESSAGE_ID]", "2684")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][CHAT_TYPE]", "P")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[PARAMS][LANGUAGE]", "ru")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[USER][ID]", "50")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[USER][NAME]", "Artem Voronov")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[USER][FIRST_NAME]", "Artem")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[USER][LAST_NAME]", "Voronov")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[USER][WORK_POSITION]", "")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "data[USER][GENDER]", "M")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "ts", "1492163064")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "auth[access_token]", "TOKEN")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "auth[expires_in]", "3600")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "auth[scope]", "imbot")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "auth[domain]", "company.bitrix24.ru")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "auth[server_endpoint]", "https://oauth.bitrix.info/rest/")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "auth[status]", "L")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "auth[client_endpoint]", "https://company.bitrix24.ru/rest/")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "auth[member_id]", "USER_ID")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "auth[user_id]", "50")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "auth[refresh_token]", "TOKEN")
    addParameter(EVENT_COMMAND_FROM_PRIVATE_CHAT_PARAMETERS, "auth[application_token]", "TOKEN")
  }

  private static addParameter(Map<String, String[]> parameters, String key, String value) {
    parameters.put(key, [value] as String[])
  }

}
